#!/usr/bin/env python3
# Generated by Mojo Compiler

def add_int(a, b):
  return a + b

def greet(name):
  return "Hello, " + name + "!"

def multiply_float(x, y):
  return x * y

def dynamic_multiply(x, y):
  return x * y

def dynamic_concat(a, b):
  return str(a) + str(b)

def process(x):
  return "정수 처리: " + str(x * 2)

def process(x):
  return "실수 처리: " + str(x * 2)

def process(x):
  return "문자열 처리: " + x + x

def greet_with_suffix(name, suffix):
  return "Hello, " + name + suffix

def divmod_custom(a, b):
  quotient = a / b
  remainder = a % b
  return str(quotient) + " (몫), " + str(remainder) + " (나머지)"

def factorial(n):
  if n <= 1:
    return 1
  return n * factorial(n - 1)

def apply_operation(a, b, operation):
  if operation == "add":
    return a + b
  elif operation == "sub":
    return a - b
  elif operation == "mul":
    return a * b
  else:
    return 0

def main():
  print("=== fn 정적 타입 함수 ===")
  result1 = add_int(5, 3)
  print("add_int(5, 3) = " + str(result1))
  greeting = greet("Mojo")
  print("greet(\"Mojo\") = " + greeting)
  float_result = multiply_float(3.5, 2.5)
  print("multiply_float(3.5, 2.5) = " + str(float_result))
  print("")
  print("=== def 동적 타입 함수 ===")
  dyn_mul = dynamic_multiply(4, 5)
  print("dynamic_multiply(4, 5) = " + str(dyn_mul))
  dyn_concat = dynamic_concat("Hello", 123)
  print("dynamic_concat(\"Hello\", 123) = " + dyn_concat)
  print("")
  print("=== 함수 오버로딩 ===")
  process_int = process(10)
  print(process_int)
  process_float = process(2.5)
  print(process_float)
  process_str = process("hi")
  print(process_str)
  print("")
  print("=== 기본값 매개변수 ===")
  greet1 = greet_with_suffix("World")
  print(greet1)
  greet2 = greet_with_suffix("World", "!!!")
  print(greet2)
  print("")
  print("=== divmod ===")
  dm = divmod_custom(17, 5)
  print("17 ÷ 5 = " + dm)
  print("")
  print("=== 재귀 함수 ===")
  fact5 = factorial(5)
  print("factorial(5) = " + str(fact5))
  fact3 = factorial(3)
  print("factorial(3) = " + str(fact3))
  print("")
  print("=== 고차 함수 (조건부 연산) ===")
  add_result = apply_operation(10, 5, "add")
  print("10 + 5 = " + str(add_result))
  sub_result = apply_operation(10, 5, "sub")
  print("10 - 5 = " + str(sub_result))
  mul_result = apply_operation(10, 5, "mul")
  print("10 * 5 = " + str(mul_result))
  print("")
  print("=== 문자열 보간 ===")
  name = "Mojo"
  version = 7
  message = "Language: " + name + ", Version: " + str(version)
  print(message)
  x = 42
  y = 8
  math_msg = "x=" + str(x) + ", y=" + str(y) + ", x+y=" + str(x + y)
  print(math_msg)

if __name__ == '__main__':
  main()