#!/usr/bin/env python3
# Generated by Mojo Compiler

def main():
  print("Line 1")
  print("Line 2")
  print("Line 3")
  print("Multiple print statements in Mojo")

if __name__ == '__main__':
  main()