#!/usr/bin/env python3
# Generated by Mojo Compiler

def greet(name):
  return "Hello, " + name + "!"

def add(a, b):
  return a + b

def main():
  message = greet("Mojo World")
  print(message)
  result = add(5, 3)
  print("5 + 3 = " + str(result))

if __name__ == '__main__':
  main()