#!/usr/bin/env python3
# Generated by Mojo Compiler

def main():
  print("=== 정수형 (Integer Types) ===")
  int_64 = 9223372036854776000
  int_32 = 2147483647
  int_16 = 32767
  int_8 = 127
  print("Int (64비트) = " + str(int_64))
  print("Int32 = " + str(int_32))
  print("Int16 = " + str(int_16))
  print("Int8 = " + str(int_8))
  print("")
  print("=== 부동소수점 (Float Types) ===")
  float_64 = 3.141592653589793
  float_32 = 3.14
  print("Float64 = " + str(float_64))
  print("Float32 = " + str(float_32))
  print("")
  print("=== 불린 (Boolean) ===")
  is_true = True
  is_false = False
  print("true = " + str(is_true))
  print("false = " + str(is_false))
  print("")
  print("=== 문자열 (String) ===")
  greeting = "Hello, Mojo!"
  multiline = "Python Syntax
C++ Performance"
  print("greeting = " + greeting)
  print("multiline:")
  print(multiline)
  print("")
  print("=== 문자 (Character) ===")
  char_a = "A"
  char_m = "M"
  print("char_a = " + char_a)
  print("char_m = " + char_m)
  print("")
  print("=== 타입 변환 (Type Casting) ===")
  number = 42
  number_str = str(number)
  print("Int to String: " + number_str)
  print("")
  print("=== 기본 연산 ===")
  a = 10
  b = 3
  print("덧셈: " + str(a + b))
  print("뺄셈: " + str(a - b))
  print("곱셈: " + str(a * b))
  print("나눗셈: " + str(a / b))
  print("나머지: " + str(a % b))

if __name__ == '__main__':
  main()