#!/usr/bin/env python3
# Generated by Mojo Compiler

def main():
  x = 5
  y = 10
  name = "Mojo"
  print("불변 변수:")
  print("x = " + str(x))
  print("y = " + str(y))
  print("name = " + name)
  print("")
  count = 0
  count = 1
  count += 5
  print("가변 변수:")
  print("count (초기값) = 0")
  print("count (할당 후) = 1")
  print("count (증감 후) = " + str(count))
  print("")
  auto_int = 42
  auto_float = 3.14
  auto_str = "hello"
  print("타입 추론:")
  print("auto_int = " + str(auto_int) + " (Int)")
  print("auto_float = " + str(auto_float) + " (Float)")
  print("auto_str = " + auto_str + " (String)")
  print("")
  explicit_int = 100
  explicit_float = 2.71828
  explicit_bool = True
  print("명시적 타입:")
  print("explicit_int = " + str(explicit_int))
  print("explicit_float = " + str(explicit_float))
  print("explicit_bool = " + str(explicit_bool))

if __name__ == '__main__':
  main()