#!/usr/bin/env python3
# Generated by Mojo Compiler

def main():
  name = "Mojo"
  version = "0.7"
  tagline = "Python Syntax, C++ Performance"
  print("Language: " + name)
  print("Version: " + version)
  print("Tagline: " + tagline)
  print("")
  print("🔥 " + name + " combines the best of both worlds!")

if __name__ == '__main__':
  main()