/**
 * Mojo Compiler - Code Generator (Python 출력)
 * 역할: AST → 실행 가능한 Python 코드 생성
 */

class CodeGenerator {
  constructor() {
    this.output = [];
    this.indentLevel = 0;
  }

  emit(line) {
    if (line === "") {
      this.output.push("");
    } else {
      this.output.push("  ".repeat(this.indentLevel) + line);
    }
  }

  indent() {
    this.indentLevel++;
  }

  dedent() {
    this.indentLevel = Math.max(0, this.indentLevel - 1);
  }

  generate(program) {
    this.output = [];
    this.indentLevel = 0;

    // 파이썬 헤더
    this.emit("#!/usr/bin/env python3");
    this.emit("# Generated by Mojo Compiler");
    this.emit("");

    // 프로그램 항목 생성
    for (const item of program.items) {
      if (item.type === "FunctionDeclaration") {
        this.generateFunction(item);
      } else if (item.type === "StructDeclaration") {
        this.generateStruct(item);
      }
      this.emit("");
    }

    // main 함수 호출
    if (this.hasMainFunction(program)) {
      this.emit("if __name__ == '__main__':");
      this.indent();
      this.emit("main()");
      this.dedent();
    }

    return this.output.join("\n");
  }

  generateFunction(fn) {
    // Generate parameters with default values and variadic support
    const params = fn.parameters.map((p) => {
      let paramStr = p.name;

      // Handle variadic parameter (*args)
      if (p.isVariadic) {
        paramStr = `*${paramStr}`;
      } else if (p.defaultValue) {
        // Handle default value (not for variadic)
        const defaultCode = this.generateExpression(p.defaultValue);
        paramStr = `${paramStr}=${defaultCode}`;
      }

      return paramStr;
    }).join(", ");

    // Handle generic types (comment them out since Python doesn't have generics)
    let signature = `def ${fn.name}(${params}):`;
    if (fn.generics && fn.generics.length > 0) {
      const generics = fn.generics.join(", ");
      signature = `# Generic types: <${generics}>\n${signature}`;
    }

    this.emit(signature);
    this.indent();

    if (fn.body.length === 0) {
      this.emit("pass");
    } else {
      for (const stmt of fn.body) {
        this.generateStatement(stmt);
      }
    }

    this.dedent();
  }

  generateStruct(struct) {
    this.emit(`class ${struct.name}:`);
    this.indent();
    this.emit("def __init__(self):");
    this.indent();
    for (const field of struct.fields) {
      this.emit(`self.${field.name} = None`);
    }
    this.dedent();
    this.dedent();
  }

  generateStatement(stmt) {
    if (stmt.type === "VariableDeclaration") {
      this.generateVarDecl(stmt);
    } else if (stmt.type === "TupleUnpacking") {
      this.generateTupleUnpacking(stmt);
    } else if (stmt.type === "Assignment") {
      this.generateAssignment(stmt);
    } else if (stmt.type === "ExpressionStatement") {
      this.generateExpressionStmt(stmt);
    } else if (stmt.type === "IfStatement") {
      this.generateIfStatement(stmt);
    } else if (stmt.type === "ForLoop") {
      this.generateForLoop(stmt);
    } else if (stmt.type === "WhileLoop") {
      this.generateWhileLoop(stmt);
    } else if (stmt.type === "ReturnStatement") {
      this.generateReturnStatement(stmt);
    } else if (stmt.type === "BreakStatement") {
      this.emit("break");
    } else if (stmt.type === "ContinueStatement") {
      this.emit("continue");
    }
  }

  generateVarDecl(decl) {
    const valueCode = decl.value ? this.generateExpression(decl.value) : "None";
    this.emit(`${decl.name} = ${valueCode}`);
  }

  generateTupleUnpacking(stmt) {
    const names = stmt.names.join(", ");
    const valueCode = stmt.value ? this.generateExpression(stmt.value) : "None";
    this.emit(`${names} = ${valueCode}`);
  }

  generateAssignment(assign) {
    const target = this.generateExpression(assign.target);
    const value = this.generateExpression(assign.value);
    const operator = assign.operator || "=";
    this.emit(`${target} ${operator} ${value}`);
  }

  generateExpressionStmt(stmt) {
    this.emit(this.generateExpression(stmt.expression));
  }

  generateIfStatement(stmt) {
    const condition = this.generateExpression(stmt.condition);
    this.emit(`if ${condition}:`);
    this.indent();
    if (stmt.thenBranch.length === 0) {
      this.emit("pass");
    } else {
      for (const s of stmt.thenBranch) {
        this.generateStatement(s);
      }
    }
    this.dedent();

    // Handle elif branches
    if (stmt.elseIfBranches && stmt.elseIfBranches.length > 0) {
      for (const elifBranch of stmt.elseIfBranches) {
        const elifCondition = this.generateExpression(elifBranch.condition);
        this.emit(`elif ${elifCondition}:`);
        this.indent();
        if (elifBranch.body.length === 0) {
          this.emit("pass");
        } else {
          for (const s of elifBranch.body) {
            this.generateStatement(s);
          }
        }
        this.dedent();
      }
    }

    if (stmt.elseBranch && stmt.elseBranch.length > 0) {
      this.emit("else:");
      this.indent();
      for (const s of stmt.elseBranch) {
        this.generateStatement(s);
      }
      this.dedent();
    }
  }

  generateForLoop(loop) {
    const iterable = this.generateExpression(loop.iterable);
    this.emit(`for ${loop.variable} in ${iterable}:`);
    this.indent();
    if (loop.body.length === 0) {
      this.emit("pass");
    } else {
      for (const stmt of loop.body) {
        this.generateStatement(stmt);
      }
    }
    this.dedent();
  }

  generateWhileLoop(loop) {
    const condition = this.generateExpression(loop.condition);
    this.emit(`while ${condition}:`);
    this.indent();
    if (loop.body.length === 0) {
      this.emit("pass");
    } else {
      for (const stmt of loop.body) {
        this.generateStatement(stmt);
      }
    }
    this.dedent();
  }

  generateReturnStatement(stmt) {
    if (stmt.value) {
      const value = this.generateExpression(stmt.value);
      this.emit(`return ${value}`);
    } else {
      this.emit("return");
    }
  }

  generateExpression(expr) {
    if (!expr) return "None";

    if (expr.type === "IntLiteral") {
      return String(expr.value);
    }

    if (expr.type === "FloatLiteral") {
      return String(expr.value);
    }

    if (expr.type === "StringLiteral") {
      // Escape special characters in string
      const escaped = expr.value
        .replace(/\\/g, "\\\\")  // Backslash
        .replace(/"/g, '\\"')    // Double quote
        .replace(/\n/g, "\\n")   // Newline
        .replace(/\t/g, "\\t")   // Tab
        .replace(/\r/g, "\\r");  // Carriage return
      return `"${escaped}"`;
    }

    if (expr.type === "BoolLiteral") {
      return expr.value ? "True" : "False";
    }

    if (expr.type === "Identifier") {
      return expr.name;
    }

    if (expr.type === "BinaryOp") {
      const left = this.generateExpression(expr.left);
      const right = this.generateExpression(expr.right);
      // Convert Mojo operators to Python equivalents
      let op = expr.operator;
      if (op === "&&") op = "and";
      else if (op === "||") op = "or";
      return `${left} ${op} ${right}`;
    }

    if (expr.type === "UnaryOp") {
      const operand = this.generateExpression(expr.operand);
      // Convert Mojo operators to Python equivalents
      let op = expr.operator;
      if (op === "!" || op === "not") {
        // Wrap operand in parens if needed
        const needsParens = expr.operand.type !== "Identifier" &&
                           expr.operand.type !== "IntLiteral" &&
                           expr.operand.type !== "FloatLiteral" &&
                           expr.operand.type !== "StringLiteral" &&
                           expr.operand.type !== "BoolLiteral";
        if (needsParens) {
          return `not (${operand})`;
        } else {
          return `not ${operand}`;
        }
      } else {
        return `${op}${operand}`;
      }
    }

    if (expr.type === "Call") {
      const func = this.generateExpression(expr.function);
      const args = expr.arguments.map((arg) => this.generateExpression(arg)).join(", ");
      return `${func}(${args})`;
    }

    if (expr.type === "ArrayLiteral") {
      const elements = expr.elements.map((e) => this.generateExpression(e)).join(", ");
      return `[${elements}]`;
    }

    if (expr.type === "TupleLiteral") {
      const elements = expr.elements.map((e) => this.generateExpression(e)).join(", ");
      // Python tuple syntax: (x,) for single element, (x, y) for multiple
      if (expr.elements.length === 1) {
        return `(${elements},)`;
      }
      return `(${elements})`;
    }

    if (expr.type === "FieldAccess") {
      const object = this.generateExpression(expr.object);
      return `${object}.${expr.field}`;
    }

    if (expr.type === "IndexAccess") {
      const object = this.generateExpression(expr.object);
      const index = this.generateExpression(expr.index);
      return `${object}[${index}]`;
    }

    if (expr.type === "StructLiteral") {
      const fields = Object.entries(expr.fields)
        .map(([key, value]) => `"${key}": ${this.generateExpression(value)}`)
        .join(", ");
      return `{${fields}}`;
    }

    if (expr.type === "MatchExpression") {
      return this.generateMatchExpression(expr);
    }

    return "error";
  }

  generateMatchExpression(match) {
    // Convert match expression to Python ternary chains
    // match x { 1 { "a" } 2 { "b" } else { "c" } }
    // becomes: ("a" if x == 1 else ("b" if x == 2 else "c"))

    const discriminant = this.generateExpression(match.discriminant);
    let result = null;

    // Build from the end backwards (last branch first for else)
    if (match.defaultBranch) {
      result = this.generateExpression(match.defaultBranch);
    } else {
      result = "None";
    }

    // Reverse iterate through branches
    for (let i = match.branches.length - 1; i >= 0; i--) {
      const branch = match.branches[i];
      const patternCode = this.generateExpression(branch.pattern);
      const armCode = this.generateExpression(branch.body);
      result = `(${armCode} if ${discriminant} == ${patternCode} else ${result})`;
    }

    return result;
  }

  hasMainFunction(program) {
    return program.items.some(
      (item) => item.type === "FunctionDeclaration" && item.name === "main"
    );
  }
}

module.exports = { CodeGenerator };
