/**
 * Mojo Compiler - Code Generator (Python 출력)
 * 역할: AST → 실행 가능한 Python 코드 생성
 */

class CodeGenerator {
  constructor() {
    this.output = [];
    this.indentLevel = 0;
  }

  emit(line) {
    if (line === "") {
      this.output.push("");
    } else {
      this.output.push("  ".repeat(this.indentLevel) + line);
    }
  }

  indent() {
    this.indentLevel++;
  }

  dedent() {
    this.indentLevel = Math.max(0, this.indentLevel - 1);
  }

  generate(program) {
    this.output = [];
    this.indentLevel = 0;

    // 파이썬 헤더
    this.emit("#!/usr/bin/env python3");
    this.emit("# Generated by Mojo Compiler");
    this.emit("");

    // 프로그램 항목 생성
    for (const item of program.items) {
      if (item.type === "FunctionDeclaration") {
        this.generateFunction(item);
      } else if (item.type === "StructDeclaration") {
        this.generateStruct(item);
      }
      this.emit("");
    }

    // main 함수 호출
    if (this.hasMainFunction(program)) {
      this.emit("if __name__ == '__main__':");
      this.indent();
      this.emit("main()");
      this.dedent();
    }

    return this.output.join("\n");
  }

  generateFunction(fn) {
    const params = fn.parameters.map((p) => p.name).join(", ");
    this.emit(`def ${fn.name}(${params}):`);
    this.indent();

    if (fn.body.length === 0) {
      this.emit("pass");
    } else {
      for (const stmt of fn.body) {
        this.generateStatement(stmt);
      }
    }

    this.dedent();
  }

  generateStruct(struct) {
    this.emit(`class ${struct.name}:`);
    this.indent();
    this.emit("def __init__(self):");
    this.indent();
    for (const field of struct.fields) {
      this.emit(`self.${field.name} = None`);
    }
    this.dedent();
    this.dedent();
  }

  generateStatement(stmt) {
    if (stmt.type === "VariableDeclaration") {
      this.generateVarDecl(stmt);
    } else if (stmt.type === "Assignment") {
      this.generateAssignment(stmt);
    } else if (stmt.type === "ExpressionStatement") {
      this.generateExpressionStmt(stmt);
    } else if (stmt.type === "IfStatement") {
      this.generateIfStatement(stmt);
    } else if (stmt.type === "ForLoop") {
      this.generateForLoop(stmt);
    } else if (stmt.type === "WhileLoop") {
      this.generateWhileLoop(stmt);
    } else if (stmt.type === "ReturnStatement") {
      this.generateReturnStatement(stmt);
    }
  }

  generateVarDecl(decl) {
    const valueCode = decl.value ? this.generateExpression(decl.value) : "None";
    this.emit(`${decl.name} = ${valueCode}`);
  }

  generateAssignment(assign) {
    const target = this.generateExpression(assign.target);
    const value = this.generateExpression(assign.value);
    this.emit(`${target} = ${value}`);
  }

  generateExpressionStmt(stmt) {
    this.emit(this.generateExpression(stmt.expression));
  }

  generateIfStatement(stmt) {
    const condition = this.generateExpression(stmt.condition);
    this.emit(`if ${condition}:`);
    this.indent();
    if (stmt.thenBranch.length === 0) {
      this.emit("pass");
    } else {
      for (const s of stmt.thenBranch) {
        this.generateStatement(s);
      }
    }
    this.dedent();

    if (stmt.elseBranch && stmt.elseBranch.length > 0) {
      this.emit("else:");
      this.indent();
      for (const s of stmt.elseBranch) {
        this.generateStatement(s);
      }
      this.dedent();
    }
  }

  generateForLoop(loop) {
    const iterable = this.generateExpression(loop.iterable);
    this.emit(`for ${loop.variable} in ${iterable}:`);
    this.indent();
    if (loop.body.length === 0) {
      this.emit("pass");
    } else {
      for (const stmt of loop.body) {
        this.generateStatement(stmt);
      }
    }
    this.dedent();
  }

  generateWhileLoop(loop) {
    const condition = this.generateExpression(loop.condition);
    this.emit(`while ${condition}:`);
    this.indent();
    if (loop.body.length === 0) {
      this.emit("pass");
    } else {
      for (const stmt of loop.body) {
        this.generateStatement(stmt);
      }
    }
    this.dedent();
  }

  generateReturnStatement(stmt) {
    if (stmt.value) {
      const value = this.generateExpression(stmt.value);
      this.emit(`return ${value}`);
    } else {
      this.emit("return");
    }
  }

  generateExpression(expr) {
    if (!expr) return "None";

    if (expr.type === "IntLiteral") {
      return String(expr.value);
    }

    if (expr.type === "FloatLiteral") {
      return String(expr.value);
    }

    if (expr.type === "StringLiteral") {
      return `"${expr.value}"`;
    }

    if (expr.type === "BoolLiteral") {
      return expr.value ? "True" : "False";
    }

    if (expr.type === "Identifier") {
      return expr.name;
    }

    if (expr.type === "BinaryOp") {
      const left = this.generateExpression(expr.left);
      const right = this.generateExpression(expr.right);
      return `${left} ${expr.operator} ${right}`;
    }

    if (expr.type === "UnaryOp") {
      const operand = this.generateExpression(expr.operand);
      return `${expr.operator}${operand}`;
    }

    if (expr.type === "Call") {
      const func = this.generateExpression(expr.function);
      const args = expr.arguments.map((arg) => this.generateExpression(arg)).join(", ");
      return `${func}(${args})`;
    }

    if (expr.type === "ArrayLiteral") {
      const elements = expr.elements.map((e) => this.generateExpression(e)).join(", ");
      return `[${elements}]`;
    }

    if (expr.type === "FieldAccess") {
      const object = this.generateExpression(expr.object);
      return `${object}.${expr.field}`;
    }

    if (expr.type === "IndexAccess") {
      const object = this.generateExpression(expr.object);
      const index = this.generateExpression(expr.index);
      return `${object}[${index}]`;
    }

    return "error";
  }

  hasMainFunction(program) {
    return program.items.some(
      (item) => item.type === "FunctionDeclaration" && item.name === "main"
    );
  }
}

module.exports = { CodeGenerator };
