#!/usr/bin/env python3
# Generated by Mojo Compiler

def add(a, b):
  result = a + b
  return result

def factorial(n):
  if n <= 1:
    return 1
  prev = factorial(n - 1)
  return n * prev

def main():
  x = add(3, 4)
  print(x)
  fact5 = factorial(5)
  print(fact5)

if __name__ == '__main__':
  main()